# Generated by Django 4.2.20 on 2025-10-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(default="guest", max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
